[package]
edition = "2021"
name = "espeak-rs"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.2.0", default-features = false, features = ["napi8", "async"] }
napi-derive = "2.2.0"
libc = "0.2"
cfile = "0.5.1"
futures = "0.3"
espeakng-sys = "0.1.0"
lazy_static = "1.4.0"

[build-dependencies]
napi-build = "1.2.1"

[dev-dependencies]
markov = "1.1.0"

[profile.release]
lto = true
