---
version: "3.9"
services:
  espeak-rs:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: >
      /bin/sh -c "cargo nextest run && npm install && npm run build && strip *.node"
  espeak-rs-cli:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: "/bin/bash"
    stdin_open: true
    tty: true
