/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function forceAlignPhonemesGraphemesList(text: string, endTimes: Array<number>, phonemesList: Array<string>, alignPhonemes: boolean): NestedChunk
export function forceAlignPhonemesGraphemes(text: string, endTimes: Array<number>, phonemesList: Array<string>, alignPhonemes: boolean): NestedChunk
export function phonemize(text: string, preservePunctuation: boolean): string
export interface NestedChunk {
  value: string
  start: number
  end: number
  startTime: number
  endTime: number
  chunks: Array<Chunk>
}
export interface Chunk {
  value: string
  start: number
  end: number
  startTime: number
  endTime: number
}
export interface PhonemeChunk {
  value: string
  valueWord: string
  start: number
  end: number
  startTime: number
  endTime: number
}
