/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function textToPhonemes(texts: Array<string>): Promise<Array<string>>
export interface Chunk {
  value: string
  valueWord: string
  start: number
  end: number
  startTime: number
  endTime: number
}
export function transformRawPhonemeTimestamps(phonemeList: Array<string>, endTimes: Array<number>): Array<Chunk>
