/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function forceAlignPhonemesGraphemes(text: string, phonemes: string, usePhonemeBounds: boolean): Promise<NestedChunk>
export function forceAlignPhonemesGraphemesList(text: string, endTimes: Array<number>, phonemesList: Array<string>, usePhonemeBounds: boolean): Promise<NestedChunk>
export function phonemize(text: string, preservePunctuation: boolean): Promise<string>
export interface NestedChunk {
  value: string
  start: number
  end: number
  startTime: number
  endTime: number
  chunks: Array<Chunk>
}
export interface Chunk {
  value: string
  start: number
  end: number
  startTime: number
  endTime: number
}
export interface PhonemeChunk {
  value: string
  valueWord: string
  start: number
  end: number
  startTime: number
  endTime: number
}
