name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on:
      labels: ubuntu-latest
    strategy:
      matrix:
        platform: [ amd64, arm64 ]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/${{ matrix.platform }}

      - name: Build
        uses: docker/build-push-action@v4
        with:
          context: .
          outputs: type=local,dest=.
          target: binaries

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: |
            rustav.*.node
            index.js
            index.d.ts
